// LUNA RAUM 3: additive tools; all project operations retain the original undo/store contracts.
Luna.version='3.0.0';$('.v2-version').textContent='3.0';document.title='LUNA RAUM 3 · Atelier · EDV Hausleitner';
const atelier={panX:0,panY:0,perspective:false,orbit:false,present:false,bookmarks:[],last:0};
const oldCameraMatrix=camera.matrix.bind(camera),oldHome=camera.home.bind(camera);
camera.home=function(){oldHome();atelier.panX=atelier.panY=0;atelier.perspective=false;syncStudio();};
camera.matrix=function(w,h){let v;if(!atelier.perspective)v=oldCameraMatrix(w,h);else{const rw=state.room.w/1000,rd=state.room.d/1000,rh=state.room.h/1000,target=[rw/2,rh*.43,rd/2],r=Math.max(rw,rd)*1.6/this.zoom,n=.03,f=100,k=1/Math.tan(Math.PI/8);this.eye=[target[0]+Math.sin(this.yaw)*Math.cos(this.pitch)*r,target[1]+Math.sin(this.pitch)*r,target[2]+Math.cos(this.yaw)*Math.cos(this.pitch)*r];this.view=M.lookAt(this.eye,target);v=M.mul([k/(w/h),0,0,0,0,k,0,0,0,0,f/(n-f),-1,0,0,n*f/(n-f),0],this.view);}v=[...v];for(let c=0;c<4;c++){v[c*4]+=atelier.panX*v[c*4+3];v[c*4+1]+=atelier.panY*v[c*4+3];}this.vp=v;this.inv=M.inverse(v);return v;};
function focusModule(){const c=state.cabinets.find(c=>c.id===selected);if(!c){toast('Wählen Sie zuerst einen Schrank aus.');return false;}if(!Luna.gpu.ready){Luna.apps.open('plan');return false;}openApp('room');view='3d';atelier.perspective=false;atelier.panX=atelier.panY=0;camera.zoom=2.8;const t=spec(c),p=Luna.room.point(c.wall,c.offset+t.w/2,t.d/2);camera.matrix(Luna.gpu.width,Luna.gpu.height);const q=M.transform(camera.vp,[p[0]/1000,(t.y+t.h/2)/1000,p[1]/1000]);atelier.panX=-q[0]/q[3];atelier.panY=-q[1]/q[3];updateViewUI();Luna.gpu.invalidate();return true;}
function syncStudio(){const b=$('#projection3');if(b){b.textContent=atelier.perspective?'Perspektive':'Parallel';b.setAttribute('aria-pressed',String(atelier.perspective));$('#orbit3').setAttribute('aria-pressed',String(atelier.orbit));$('#present3').setAttribute('aria-pressed',String(atelier.present));}}
function projection(){atelier.perspective=!atelier.perspective;atelier.panX=atelier.panY=0;camera.zoom=1;syncStudio();Luna.gpu.invalidate();}
function presentation(value=!atelier.present){atelier.present=value;document.body.classList.toggle('presentation3',value);if(value)openApp('room');syncStudio();requestAnimationFrame(()=>Luna.gpu.resize());}
function orbit(value=!atelier.orbit){atelier.orbit=value;atelier.last=0;syncStudio();if(value){if(!Luna.gpu.ready){atelier.orbit=false;syncStudio();toast('Automatischer Orbit benötigt WebGPU.');return;}requestAnimationFrame(tickOrbit);}}
function tickOrbit(t){if(!atelier.orbit)return;if(document.hidden){atelier.last=0;requestAnimationFrame(tickOrbit);return;}const dt=atelier.last?Math.min(t-atelier.last,50):0;atelier.last=t;if(effectiveView()==='3d'&&!$('#window').hidden&&!document.querySelector('dialog[open]')){camera.yaw+=dt*.00007;Luna.gpu.invalidate();}requestAnimationFrame(tickOrbit);}
const studioStyle=document.createElement('style');studioStyle.textContent=`#studio3{display:flex;gap:5px;align-items:center;padding:7px 14px;background:#f7f9fb;border-bottom:1px solid #dde6ed;overflow-x:auto;flex-shrink:0}#studio3 button{white-space:nowrap;font-size:11px;min-height:29px;padding:4px 9px}#studio3 button[aria-pressed=true]{background:#0078c8;color:white}#studio3 .hint3{margin-left:auto;font-size:10px;color:#6b8190;white-space:nowrap}.presentation3 .sidebar,.presentation3 .inspector,.presentation3 #tools2,.presentation3 #projectHeader{display:none!important}.presentation3 #studio3 .hint3{display:none}.presentation3 #window{inset:8px 8px 52px!important;width:auto!important;height:auto!important}.presentation3 #stage{min-height:380px}#bookmarkList3 button{display:block;width:100%;text-align:left;margin:6px 0}#styleCards3{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}#styleCards3 button{min-height:100px;text-align:left;line-height:1.8}#styleCards3 i{display:block;height:26px;border-radius:5px;margin-bottom:8px}#help3{line-height:1.8}#help3 kbd{background:#e9eff4;border:1px solid #ccd9e2;border-radius:4px;padding:1px 5px}#featureSearch3{width:100%;margin:12px 0}#featureList3{max-height:42vh;overflow:auto;padding-left:22px;font-size:12px;line-height:1.7}#detailDialog:has(#featureList3){width:min(780px,92vw)}@media(max-width:700px){#studio3{padding:6px;gap:4px}#studio3 .hint3{display:none}#styleCards3{grid-template-columns:1fr}.presentation3 #stage{min-height:250px}}`;document.head.append(studioStyle);
$('#tools2').insertAdjacentHTML('afterend',`<div id="studio3"><button id="focus3" title="Auswahl vergrößern · F">Fokus</button><button id="projection3" aria-pressed="false">Parallel</button><button id="orbit3" aria-pressed="false">Orbit ▶</button><button id="present3" aria-pressed="false">Präsentieren</button><button id="bookmarks3">Blickpunkte</button><button id="styles3">Stilpakete</button><button id="report3">Gesprächsblatt ↓</button><button id="helpButton3">Hilfe · Funktionen</button><span class="hint3">Shift + Ziehen: verschieben · F: Fokus · Esc: zurück</span></div>`);
$('#focus3').onclick=focusModule;$('#projection3').onclick=projection;$('#orbit3').onclick=()=>orbit();$('#present3').onclick=()=>presentation();
let panPointer=null;const drawing3=$('#drawing');drawing3.addEventListener('pointerdown',e=>{if(e.shiftKey||e.button===1){if(effectiveView()!=='3d')return;e.stopImmediatePropagation();e.preventDefault();panPointer={id:e.pointerId,x:e.clientX,y:e.clientY};drawing3.setPointerCapture(e.pointerId);}},true);drawing3.addEventListener('pointermove',e=>{if(!panPointer)return;e.stopImmediatePropagation();atelier.panX=clamp(atelier.panX+2*(e.clientX-panPointer.x)/Luna.gpu.width,-5,5);atelier.panY=clamp(atelier.panY-2*(e.clientY-panPointer.y)/Luna.gpu.height,-5,5);panPointer.x=e.clientX;panPointer.y=e.clientY;Luna.gpu.invalidate();},true);drawing3.addEventListener('pointerup',e=>{if(panPointer){panPointer=null;e.stopImmediatePropagation();drawing3.releasePointerCapture(e.pointerId);}},true);drawing3.addEventListener('pointercancel',()=>panPointer=null,true);
function readBookmarks(){try{const a=JSON.parse(localStorage.getItem('luna.raum.views.v3')||'[]');atelier.bookmarks=Array.isArray(a)?a.filter(x=>x&&typeof x.name==='string'&&[x.yaw,x.pitch,x.zoom,x.panX,x.panY].every(Number.isFinite)).slice(0,8):[];}catch(e){atelier.bookmarks=[];}}
function saveBookmark(name){if(!name.trim())throw Error('Bitte benennen Sie den Blickpunkt.');if(atelier.bookmarks.length>=8)throw Error('Maximal acht Blickpunkte. Entfernen Sie zuerst einen.');const next=[...atelier.bookmarks,{name:name.trim().slice(0,70),yaw:camera.yaw,pitch:camera.pitch,zoom:camera.zoom,panX:atelier.panX,panY:atelier.panY,perspective:atelier.perspective}];try{localStorage.setItem('luna.raum.views.v3',JSON.stringify(next));}catch(e){throw Error('Der Browser erlaubt hier keine dauerhafte Speicherung.');}atelier.bookmarks=next;}
function restoreBookmark(i){const p=atelier.bookmarks[i];if(!p)return;openApp('room');view='3d';camera.yaw=p.yaw;camera.pitch=clamp(p.pitch,.15,1.35);camera.zoom=clamp(p.zoom,.35,6);atelier.panX=clamp(p.panX,-5,5);atelier.panY=clamp(p.panY,-5,5);atelier.perspective=!!p.perspective;updateViewUI();syncStudio();Luna.gpu.invalidate(true);}
function bookmarksDialog(){readBookmarks();detailDialog('Ihre Blickpunkte',`<p>Bis zu acht Kamerapositionen, lokal auf diesem Gerät. Die Raumgeometrie wird dabei nicht kopiert.</p><div class="field"><label>Aktuellen Blick benennen</label><input id="viewName3" maxlength="70" placeholder="Zum Beispiel: Blick auf die Insel"></div><div id="bookmarkList3">${atelier.bookmarks.map((b,i)=>`<div class="row"><button type="button" data-view3="${i}">${i+1}. ${esc(b.name)}</button><button type="button" data-removeview3="${i}" aria-label="Blickpunkt entfernen">×</button></div>`).join('')||'<p>Noch keine Blickpunkte gespeichert.</p>'}</div>`,()=>saveBookmark($('#viewName3').value));$$('[data-view3]').forEach(b=>b.onclick=()=>{restoreBookmark(+b.dataset.view3);$('#detailDialog').close();});$$('[data-removeview3]').forEach(b=>b.onclick=()=>{const next=atelier.bookmarks.filter((_,i)=>i!==+b.dataset.removeview3);try{localStorage.setItem('luna.raum.views.v3',JSON.stringify(next));atelier.bookmarks=next;$('#detailDialog').close();bookmarksDialog();}catch(e){$('#detailError').textContent='Speichern nicht möglich.';}});}
const stylePackages=[{name:'Eiche · Atelier',colors:['#b59266','#dfd8c6','#1e3a4b'],finish:'oak',frontStyle:'ribbed',handles:'black',worktop:'limestone',floor:'navy',daylight:80},{name:'Salbei · Messing',colors:['#788975','#bba76e','#cecbbf'],finish:'sage',frontStyle:'shaker',handles:'brass',worktop:'white',floor:'stone',daylight:68},{name:'Graphit · Nuss',colors:['#384247','#8d6649','#d2c8b5'],finish:'graphite',frontStyle:'flat',handles:'steel',worktop:'oak',floor:'oak',daylight:90}];
function applyStyle(i){const p=stylePackages[i];if(!p)return;commit(()=>{state.finish=p.finish;for(const k of ['frontStyle','handles','worktop','floor','daylight'])settings()[k]=p[k];for(const c of state.cabinets)for(const k of ['finish','frontStyle','handles'])delete c[k];});toast(p.name+' angewendet. Rückgängig bleibt verfügbar.');}
function stylesDialog(){detailDialog('Drei abgestimmte Stilpakete',`<p>Ändert Fronten, Griffe, Platte, Boden und Tageslicht gemeinsam. Individuelle Materialübersteuerungen werden zurückgesetzt; Maße bleiben erhalten.</p><div id="styleCards3">${stylePackages.map((s,i)=>`<button type="button" data-style3="${i}"><i style="background:linear-gradient(90deg,${s.colors[0]} 0 40%,${s.colors[1]} 40% 70%,${s.colors[2]} 70%)"></i><strong>${s.name}</strong><br>Materialien gemeinsam ändern</button>`).join('')}</div>`,()=>{});$$('[data-style3]').forEach(b=>b.onclick=()=>{applyStyle(+b.dataset.style3);$('#detailDialog').close();});}
function makeReport(){const t=Luna.takeoff.calculate(),p=state.project||{},lines=['LUNA RAUM · GESPRÄCHSBLATT',state.name,'Referenz: '+(p.reference||'—'),'Ansprechperson: '+(p.contact||'—'),'',`Raum: ${state.room.w} × ${state.room.d} × ${state.room.h} mm`,`Boden: ${dec(t.floor)} m² · Wände netto: ${dec(t.wall)} m²`,`Arbeitsplatte: ${dec(t.top)} lm · Sockel: ${dec(t.plinth)} lm`,`Demo-Richtwert: ${euro(t.sum)} (ohne Geräte, Montage und USt.)`,'','MÖBEL'];state.cabinets.forEach((c,i)=>{const s=spec(c);lines.push(`${i+1}. ${s.name} · ${s.w} × ${s.h} × ${s.d} mm · ${c.wall==='I'?'Insel':'Wand '+c.wall} +${c.offset} mm · ${finishFor(c).name}`);});lines.push('','ANSCHLÜSSE');state.services.forEach(s=>lines.push(`${SERVICES[s.type].name||s.type} · Wand ${s.wall} · Position ${s.offset} mm · Höhe ${s.h} mm · ${s.note}`));lines.push('','GESPRÄCHSNOTIZEN');state.notes.forEach(n=>lines.push(`${n.done?'[x]':'[ ]'} ${n.text}`));lines.push('','DEMO · keine Fertigungsfreigabe · kein BIM · kein verbindliches Angebot.','Maße, Installationen, Beschläge, Öffnungsradien und Mengen vor Ort prüfen.','EDV Hausleitner GmbH Linz');return lines.join('\n');}
$('#bookmarks3').onclick=bookmarksDialog;$('#styles3').onclick=stylesDialog;$('#report3').onclick=()=>download('Luna-Raum-Gespraechsblatt.txt',makeReport(),'text/plain;charset=utf-8');
const featureNames=('Auszugsschrank-Katalog|Breiter Spülenschrank|Kochfeldschränke|Backofen-Hochschrank|Kühlschrank-Hochschrank|Vorratsschrank mit Böden|Offene Regale|Vitrinenmodule|Dunstabzug-Module|Katalog-Volltextsuche|Geräte-Katalogfilter|Drag-and-drop aus Katalog|Individuelle Schrankbreite|Individuelle Schranktiefe|Individuelle Schrankhöhe|Individuelle Montagehöhe|Material je Schrank|Frontstil je Schrank|Griffe je Schrank|Türanschlag links/rechts|Einlegeboden-Anzahl|Auszugs-Anzahl|Parametrisches Duplizieren|Modulmaße zurücksetzen|Einzelne Front öffnen|Alle Fronten öffnen|Sichtbare Korpus-Innenräume|Ausgezogene Schubladen mit Einteilungen|Shaker-Rahmenfronten|Gerillte Fronten mit Geometrie|Fünf Frontmaterialien|Vier Griffausführungen|Vier Plattenmaterialien|Variable Arbeitsplattendicke|Variabler Plattenüberstand|Drei Bodenoberflächen|Tageslichtregler|Schaltbare Unterbauleuchten|Echte Schlagschatten|Detailstufe umschalten|Möbel-Positionsnummern|Getrennte Zeichnungsebenen|Feines 10/50/100-mm-Raster|Insel platzieren|Insel verschieben|Insel um 90 Grad drehen|Insel mit Modulen bestücken|Atelier-Demoszene|Zweizeiler-Demoszene|Anschlüsse in 3D und Plan|Anschlüsse bearbeiten|Anschlüsse als CSV|Eigene Zweipunkt-Messungen|Messlinien löschen|Planprüfung mit Hinweisen|Inselabstand-Hinweis|Wasseranschluss-Hinweis|Plattenhöhen-Hinweis|Prüfhinweise als Notiz|Entwurfsvarianten sichern|Varianten wiederherstellen|Variantenpreise vergleichen|Varianten exportieren|Schematische Bauteilvorschau|Bauteil-CSV|Bauteilzeile wählt Möbel|Arbeitsplattenfläche|Bemaßter SVG-Grundriss|Aktuelle Ansicht als PNG|Projektinformationen|Zoom bis 600 Prozent|Auswahl fokussieren|Kamera seitlich verschieben|Echte perspektivische Kamera|Ruhiger automatischer Orbit|Präsentationsmodus|Lokale Kamerablickpunkte|Blickpunkte wiederherstellen und löschen|Abgestimmte Stilpakete|Gesprächsblatt als Text|Tastatur-Kamerasteuerung|Durchsuchbares Funktionsverzeichnis').split('|');
function helpDialog(){detailDialog('LUNA RAUM 3 · '+featureNames.length+' Erweiterungen',`<div id="help3"><p><kbd>F</kbd> Auswahl vergrößern · <kbd>P</kbd> Präsentation · <kbd>Esc</kbd> zurück<br><kbd>Shift</kbd> + Ziehen: Kamera verschieben · Mausrad: Zoom bis 600 %<br><kbd>O</kbd> Front öffnen · <kbd>M</kbd> Messen · <kbd>Strg/Cmd+D</kbd> duplizieren<br><kbd>Alt</kbd> + Pfeiltasten: Kamera drehen · <kbd>Home</kbd> Gesamtansicht</p><p>Alle Projekte bleiben lokal. Exportieren Sie wichtige Entwürfe als JSON. Nicht als Fertigungsplan verwenden.</p><input id="featureSearch3" type="search" placeholder="Funktion suchen …" aria-label="Funktion suchen"><ol id="featureList3">${featureNames.map((n,i)=>`<li data-feature3="${esc(n.toLowerCase())}" value="${i+1}">${esc(n)}</li>`).join('')}</ol></div>`,()=>{});$('#featureSearch3').oninput=e=>$$('[data-feature3]').forEach(n=>n.hidden=!n.dataset.feature3.includes(e.target.value.toLowerCase()));}
$('#helpButton3').onclick=helpDialog;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){orbit(false);if(atelier.present)presentation(false);return;}if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.key.toLowerCase()==='f'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();focusModule();}if(e.key.toLowerCase()==='p'&&!e.ctrlKey&&!e.metaKey){e.preventDefault();presentation();}if(e.key==='Home'){e.preventDefault();camera.home();Luna.gpu.invalidate(true);}if(e.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();if(e.key==='ArrowLeft')camera.yaw-=.1;if(e.key==='ArrowRight')camera.yaw+=.1;if(e.key==='ArrowUp')camera.pitch=clamp(camera.pitch+.08,.15,1.35);if(e.key==='ArrowDown')camera.pitch=clamp(camera.pitch-.08,.15,1.35);Luna.gpu.invalidate();}},true);
Luna.studio={state:atelier,focus:focusModule,presentation,projection,orbit,saveBookmark,restoreBookmark,readBookmarks,applyStyle,report:makeReport,features:featureNames,help:helpDialog};syncStudio();
